@host = http://localhost:5240

GET {{host}}/api/tasks
Content-Type: application/json
Accept: application/json

###

POST {{host}}/api/tasks
Content-Type: application/json
Accept: application/json

{
    "title": "Estudar POST",
    "description": "Criar primeira tarefa usando arquivo .http"
}

###